import * as vscode from 'vscode';
import * as fs from 'fs';
import * as path from 'path';
import { EnvironmentInfo } from '../ToolScanner';
import { AgentOverride, McpIntegrationConfig, AllDocSources, DevOpsConfig, GuidelinesConfig } from '../agentSync/types';
import { ConnectionState } from './welcomeTypes';
import { ProfileDefinition } from '../ProfileManager';

/**
 * Reading and writing of the workspace project-context files:
 * `now.config.json` (read-only Fluent app facts) and
 * `.vscode/nowdev-ai-config.json` (auto-generated agent context).
 */

export interface FluentAppInfo {
    scope: string;
    scopeId: string;
    name: string;
    scopePrefix: string;
    numericScopeId: string;
}

export function readNowConfig(workspaceRoot: string): FluentAppInfo | null {
    const configPath = path.join(workspaceRoot, 'now.config.json');
    try {
        if (!fs.existsSync(configPath)) { return null; }
        const raw = fs.readFileSync(configPath, 'utf-8');
        const config = JSON.parse(raw);
        if (!config.scope) { return null; }

        let scopePrefix = '';
        let numericScopeId = '';
        const scopeMatch = config.scope.match(/^(\w+?)_(\d+)_/);
        if (scopeMatch) {
            scopePrefix = scopeMatch[1];
            numericScopeId = scopeMatch[2];
        }

        return {
            scope: config.scope || '',
            scopeId: config.scopeId || '',
            name: config.name || '',
            scopePrefix,
            numericScopeId,
        };
    } catch (err) {
        console.error('Failed to read now.config.json:', err);
        return null;
    }
}

/** Everything the generated config file is built from — passed explicitly so this module owns no state. */
export interface NowDevConfigSnapshot {
    settings: { instanceUrl: string; customInstructionsFile: string };
    customInstructionsContent: string;
    fluentApp: FluentAppInfo | null;
    environmentInfo: EnvironmentInfo | null;
    selectedMcp: string[];
    mcpUserDismissed: string[];
    mcpIntegrationConfigs: Record<string, McpIntegrationConfig>;
    allDocSources: AllDocSources;
    devopsConfig: DevOpsConfig;
    guidelinesConfig: GuidelinesConfig;
    agentOverrides: Record<string, AgentOverride>;
    activeProfileId: string;
    profileInstructionsOverrides: Record<string, string>;
    customProfiles: ProfileDefinition[];
}

/**
 * Writes `.vscode/nowdev-ai-config.json`, preserving agent-written fields.
 */
export function writeNowDevConfigFile(workspaceRoot: string, snapshot: NowDevConfigSnapshot): void {
    const vscodePath = path.join(workspaceRoot, '.vscode');
    const configPath = path.join(vscodePath, 'nowdev-ai-config.json');

    const configData: Record<string, unknown> = {
        _comment: 'Auto-generated by NowDev AI Toolbox. Agents read this file for project context. Do not edit manually.',
        instanceUrl: snapshot.settings.instanceUrl,
    };

    if (snapshot.fluentApp) {
        configData.fluentApp = {
            scope: snapshot.fluentApp.scope,
            scopeId: snapshot.fluentApp.scopeId,
            name: snapshot.fluentApp.name,
            scopePrefix: snapshot.fluentApp.scopePrefix,
            numericScopeId: snapshot.fluentApp.numericScopeId,
        };
    }

    if (snapshot.customInstructionsContent) {
        configData.customInstructions = snapshot.customInstructionsContent;
    }

    if (snapshot.environmentInfo) {
        const env = snapshot.environmentInfo;
        const enabledTools: Record<string, { version: string; label: string; description: string }> = {};
        for (const [key, tool] of Object.entries(env.tools)) {
            if (tool.enabled && (tool.available || tool.manualOverride)) {
                enabledTools[key] = {
                    version: tool.version,
                    label: tool.label,
                    description: tool.description,
                };
            }
        }
        configData.environment = {
            os: env.os,
            osVersion: env.osVersion,
            arch: env.arch,
            shell: env.shell,
            availableTools: enabledTools,
        };
    }

    // MCP server selection
    configData.mcpIntegrations = snapshot.selectedMcp;

    // Servers the user explicitly disabled — preserved so auto-enable doesn't re-add them
    if (snapshot.mcpUserDismissed.length > 0) {
        configData.mcpUserDismissed = snapshot.mcpUserDismissed;
    }

    // Per-MCP-server access configs
    if (Object.keys(snapshot.mcpIntegrationConfigs).length > 0) {
        configData.mcpIntegrationConfigs = snapshot.mcpIntegrationConfigs;
    }

    // Unified documentation sources (localPath and lastSynced are derived at runtime, not persisted)
    configData.allDocSources = {
        ...snapshot.allDocSources,
        productDocs: {
            ...snapshot.allDocSources.productDocs,
            localPath: undefined,
            lastSynced: undefined,
        },
    };

    // Work-item / DevOps integration config
    configData.devopsConfig = snapshot.devopsConfig;

    // Instance-backed agent guidelines
    if (snapshot.guidelinesConfig.enabled || snapshot.guidelinesConfig.selectedArticles.length > 0) {
        configData.guidelines = snapshot.guidelinesConfig;
    }

    // Per-agent overrides
    if (Object.keys(snapshot.agentOverrides).length > 0) {
        configData.agentOverrides = snapshot.agentOverrides;
    }

    // Active user profile
    configData.activeProfile = snapshot.activeProfileId;

    // Profile instruction overrides — only written when the user has customized at least one profile.
    // Built-in defaults are never written here so user customizations survive extension upgrades.
    if (Object.keys(snapshot.profileInstructionsOverrides).length > 0) {
        configData.profileInstructionsOverrides = snapshot.profileInstructionsOverrides;
    }

    // Company-provided custom profiles — the extension seam alongside the built-in profiles.
    // Preserved verbatim so hand-authored entries in the config file survive regeneration.
    configData.customProfiles = snapshot.customProfiles;

    // Preserve agent-written fields (e.g. memoryLocation) that should not be overwritten
    try {
        if (fs.existsSync(configPath)) {
            const existing = JSON.parse(fs.readFileSync(configPath, 'utf-8'));
            if (existing.memoryLocation) {
                configData.memoryLocation = existing.memoryLocation;
            }
            if (existing.guidelines && !configData.guidelines) {
                configData.guidelines = existing.guidelines;
            }
        }
    } catch { /* ignore parse errors */ }

    try {
        if (!fs.existsSync(vscodePath)) {
            fs.mkdirSync(vscodePath, { recursive: true });
        }
        fs.writeFileSync(configPath, JSON.stringify(configData, null, 2) + '\n', 'utf-8');
    } catch (err) {
        console.error('Failed to write nowdev-ai-config.json:', err);
    }
}

export function writeConnectionStatusToConfig(workspaceRoot: string, state: ConnectionState): void {
    const configPath = path.join(workspaceRoot, '.vscode', 'nowdev-ai-config.json');
    try {
        if (!fs.existsSync(configPath)) { return; }
        const existing = JSON.parse(fs.readFileSync(configPath, 'utf-8'));
        existing.instanceConnection = {
            reachable: state.reachable,
            statusCode: state.statusCode,
            responseTime: state.responseTime,
            error: state.error,
            checkedAt: state.timestamp,
        };
        fs.writeFileSync(configPath, JSON.stringify(existing, null, 2) + '\n', 'utf-8');
    } catch { /* ignore */ }
}
